
themes = {
            "catppuccin_mocha": { # Darkest
                "base": "#1e1e2e",
                "mantle": "#181825",
                "crust": "#11111b",
                "surface0": "#313244",
                "surface1": "#45475a",
                "surface2": "#585b70",
                "overlay0": "#6c7086",
                "overlay1": "#7f849c",
                "overlay2": "#9399b2",
                "text": "#cdd6f4",
                "subtext0": "#a6adc8",
                "subtext1": "#bac2de",
                "accent_rosewater": "#f5e0dc",
                "accent_flamingo": "#f2cdcd",
                "accent_pink": "#f5c2e7",
                "accent_mauve": "#cba6f7",
                "accent_red": "#f38ba8",
                "accent_maroon": "#eba0ac",
                "accent_peach": "#fab387",
                "accent_yellow": "#f9e2af",
                "accent_green": "#a6e3a1",
                "accent_teal": "#94e2d5",
                "accent_sky": "#89dceb",
                "accent_sapphire": "#74c7ec",
                "accent_blue": "#89b4fa",
                "accent_lavender": "#b4befe",
            },
            "catppuccin_macchiato": { # Darker
                "base": "#24273a",
                "mantle": "#1e2030",
                "crust": "#181926",
                "surface0": "#363a4f",
                "surface1": "#494d64",
                "surface2": "#5b6078",
                "overlay0": "#6e738d",
                "overlay1": "#8087a2",
                "overlay2": "#939ab7",
                "text": "#cad3f5",
                "subtext0": "#a5adce",
                "subtext1": "#b8c0e0",
                "accent_rosewater": "#f4dbd6",
                "accent_flamingo": "#f0c6c6",
                "accent_pink": "#f5bde6",
                "accent_mauve": "#c6a0f6",
                "accent_red": "#ed8796",
                "accent_maroon": "#ee99a0",
                "accent_peach": "#f5a97f",
                "accent_yellow": "#eed49f",
                "accent_green": "#a6da95",
                "accent_teal": "#8bd5ca",
                "accent_sky": "#91d7e3",
                "accent_sapphire": "#7dc4e4",
                "accent_blue": "#8aadf4",
                "accent_lavender": "#b7bdf8",
            },
            "catppuccin_frappe": { # Medium-Dark
                "base": "#303446",
                "mantle": "#292c3c",
                "crust": "#232634",
                "surface0": "#414559",
                "surface1": "#51576d",
                "surface2": "#626880",
                "overlay0": "#737994",
                "overlay1": "#838ba7",
                "overlay2": "#949cbb",
                "text": "#c6d0f5",
                "subtext0": "#a5adce",
                "subtext1": "#b5bfe2",
                "accent_rosewater": "#f2d5cf",
                "accent_flamingo": "#eebebe",
                "accent_pink": "#f4b8e4",
                "accent_mauve": "#ca9ee6",
                "accent_red": "#e78284",
                "accent_maroon": "#ea999c",
                "accent_peach": "#ef9f76",
                "accent_yellow": "#e5c890",
                "accent_green": "#a6d189",
                "accent_teal": "#81c8be",
                "accent_sky": "#99d1db",
                "accent_sapphire": "#85c1dc",
                "accent_blue": "#8caaee",
                "accent_lavender": "#babbf1",
            },
            "catppuccin_latte": { # Light
                "base": "#eff1f5",
                "mantle": "#e6e9ef",
                "crust": "#dce0e8",
                "surface0": "#ccd0da",
                "surface1": "#bcc0cc",
                "surface2": "#acb0be",
                "overlay0": "#9ca0b0",
                "overlay1": "#8c8fa1",
                "overlay2": "#7c7f93",
                "text": "#4c4f69",
                "subtext0": "#6c6f85",
                "subtext1": "#5c5f77",
                "accent_rosewater": "#dc8a78",
                "accent_flamingo": "#dd7878",
                "accent_pink": "#ea76cb",
                "accent_mauve": "#8839ef",
                "accent_red": "#d20f39",
                "accent_maroon": "#e64553",
                "accent_peach": "#fe640b",
                "accent_yellow": "#df8e1d",
                "accent_green": "#40a02b",
                "accent_teal": "#179299",
                "accent_sky": "#04a5e5",
                "accent_sapphire": "#209fb5",
                "accent_blue": "#1e66f5",
                "accent_lavender": "#7287fd",
            },
            "dracula": {
                "base": "#282a36",
                "surface0": "#44475a",
                "surface1": "#6272a4",
                "text": "#f8f8f2",
                "subtext0": "#6272a4",
                "foreground": "#f8f8f2",
                "comment": "#6272a4",
                "selection": "#44475a",
                "currentLine": "#44475a",
                "accent_cyan": "#8be9fd",
                "accent_green": "#50fa7b",
                "accent_orange": "#ffb86c",
                "accent_pink": "#ff79c6",
                "accent_purple": "#bd93f9",
                "accent_red": "#ff5555",
                "accent_yellow": "#f1fa8c",
            },
            "one_dark": {
                "base": "#282c34",
                "surface0": "#3a3f4b",
                "surface1": "#5c6370",
                "text": "#abb2bf",
                "subtext0": "#5c6370",
                "foreground": "#abb2bf",
                "comment": "#5c6370",
                "selection": "#3e4451",
                "accent_green": "#98c379",
                "accent_orange": "#d19a66",
                "accent_purple": "#c678dd",
                "accent_keyword": "#c678dd",
                "accent_blue": "#61afef",
                "accent_yellow": "#e5c07b",
                "parameter": "#abb2bf",
                "operator": "#abb2bf",
                "punctuation": "#abb2bf",
                "accent_red": "#e06c75",
            },
            "tokyo_night": {
                "base": "#24283b",
                "surface0": "#2f3549",
                "surface1": "#414868",
                "text": "#c0caf5",
                "subtext0": "#565f89",
                "foreground": "#c8d3f5",
                "comment": "#565f89",
                "selection": "#3b4261",
                "accent_green": "#9ece6a",
                "accent_orange": "#ff9e64",
                "accent_purple": "#c6a0f6",
                "accent_keyword": "#bb9af7",
                "accent_blue": "#7aa2f7",
                "accent_yellow": "#e0af68",
                "parameter": "#c8d3f5",
                "operator": "#c8d3f5",
                "punctuation": "#c8d3f5",
                "accent_red": "#f7768e",
            },
            "night_owl": {
                "base": "#011627",
                "surface0": "#112630",
                "surface1": "#2d3f44",
                "text": "#d6deeb", # General text color
                "subtext0": "#637777", # Less prominent text
                "foreground": "#d6deeb", # Default foreground for code elements
                "comment": "#637777",
                "selection": "#1d3b53",
                "accent_green": "#addb67", # Strings, etc.
                "accent_orange": "#f78c6c", # Numbers, constants
                "accent_purple": "#c792ea", # Keywords, special constants
                "accent_keyword": "#c792ea", # Explicitly for keywords if needed
                "accent_blue": "#82aaff", # Functions, classes
                "accent_yellow": "#ffcb8b", # Variables, attributes
                "parameter": "#d6deeb", # Function parameters
                "operator": "#c792ea", # Operators
                "punctuation": "#d6deeb", # Punctuation like brackets, commas
                "accent_red": "#f07178", # Errors, important warnings
            },
            "gruvbox_dark": {
                "base": "#282828",
                "surface0": "#3c3836",
                "surface1": "#504945",
                "text": "#ebdbb2",
                "subtext0": "#a89984",
                "foreground": "#ebdbb2",
                "comment": "#928374",
                "selection": "#504945",
                "accent_green": "#b8bb26",
                "accent_orange": "#fe8019",
                "accent_purple": "#d3869b",
                "accent_keyword": "#fb4934", # Often red in gruvbox
                "accent_blue": "#83a598",
                "accent_yellow": "#fabd2f",
                "parameter": "#ebdbb2",
                "operator": "#ebdbb2",
                "punctuation": "#ebdbb2",
                "accent_red": "#fb4934",
            },
            "solarized_dark": {
                "base": "#002b36",
                "surface0": "#073642",
                "surface1": "#586e75",
                "text": "#839496",
                "subtext0": "#586e75",
                "foreground": "#839496",
                "comment": "#586e75",
                "selection": "#073642",
                "accent_green": "#859900",
                "accent_orange": "#cb4b16",
                "accent_purple": "#d33682",
                "accent_keyword": "#cb4b16", # Often orange
                "accent_blue": "#268bd2",
                "accent_yellow": "#b58900",
                "parameter": "#93a1a1",
                "operator": "#93a1a1",
                "punctuation": "#93a1a1",
                "accent_red": "#dc322f",
            },
            "github_dark": {
                "base": "#0d1117",
                "surface0": "#161b22",
                "text": "#da3633",
                "surface1": "#8b949e",
                "accent_blue": "#58a6ff",
                "accent_blue_hover": "#1f6feb",
                "selection": "#30363d",
                "accent_green": "#238636",
                "accent_yellow": "#d29922",
                "accent_red": "#da3633",
                "accent_purple": "#8250df",
                "diff_add": "#28a745",
                "diff_remove": "#cb2431",
                "diff_change": "#e6b819",
                "code_background": "#161b22",
                "code_text": "#c9d1d9",
                "code_keyword": "#f97583",
                "code_string": "#9ecbff",
                "code_comment": "#6e7781",
                "code_number": "#79c0ff",
                "code_function": "#d2a8ff",
                "code_variable": "#c9d1d9",
                "code_operator": "#c9d1d9",
            },
            "moneygazer": {
                "base": "#060b13",
                "surface0": "#0c1527",
                "surface1": "#3e6ac1",
                "text": "#fc9d03",
                "subtext0": "#657b83",
                "foreground": "#eee8d5",
                "comment": "#93a1a1",
                "selection": "#002433",
                "accent_pink": "#d33682",
                "accent_blue": "#268bd2",
                "accent_green": "#859900",
                "accent_yellow": "#b58900",
                "accent_orange": "#cb4b16",
                "parameter": "#6c71c4",
                "operator": "#839496",
                "punctuation": "#93a1a1",
            },
        }