---
name: Bug Report
description: File a bug or issue report.
title: '[Bug]: '
labels: ['Type: Bug']
body:
  - type: markdown
    attributes:
      value: |
        This can mean latest release, pre-release, or git commit.
  - type: checkboxes
    attributes:
      label: Bug Report Checklist
      description: Please check all of the following boxes that apply to your issue.
      options:
        - label: I have read the documentation.
        - label: I have searched for existing issues and confirmed this is not a duplicate.
        - label: I am using the latest version of SnipStudio (or specify commit/release).
        - label: I can consistently reproduce this issue.

  - type: input
    attributes:
      label: Snip Version
      description: What version of SnipStudio are you using? (e.g., v1.0.0, commit hash)
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System & Version
      description: What operating system and version are you running SnipStudio on? (e.g., Windows 10, macOS 13.4, Ubuntu 22.04)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Clear and concise description of the problem. Attach screenshots if needed, and include any error messages you see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Clear and concise description of what you think should happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Minimal steps needed for the problem to occur.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: Please provide any relevant logs that could help diagnose the issue. This could include error logs, console output, or crash reports.