# name: Format with Ruff

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   format:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Python 3.12
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"
#       - name: Install ruff
#         run: pip install ruff
#       - name: Run ruff --format
#         run: ruff format .
#       - name: Commit changes
#         run: |
#           git diff --check
#           if git diff --quiet; then
#             echo "No changes to commit"
#           else
#             git config --local user.email "github-actions[bot]@users.noreply.github.com"
#             git config --local user.name "github-actions[bot]"
#             git add .
#             git commit -m "Apply ruff formatting"
#             git push -f origin main
#           fi
name: Format with Ruff

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants GITHUB_TOKEN write access to the repository
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use the token with write access
          persist-credentials: true  # Ensure credentials are persisted for git push

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff --format
        run: ruff format .

      - name: Commit changes
        run: |
          git diff --check
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add .
            git commit -m "Apply ruff formatting"
            git push origin main 
          fi