name: Build and Release SnipStudio

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build_executables:
    name: Build executables on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: snipstudio.exe
            artifact_name: snipstudio-windows
          - os: ubuntu-latest
            output_name: snipstudio
            artifact_name: snipstudio-linux
          - os: macos-latest
            output_name: snipstudio
            artifact_name: snipstudio-macos
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name ${{ matrix.output_name }} snipstudio.py
          
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.output_name }}
          retention-days: 7

  create_tag_release:
    name: Create GitHub Release from Tag
    needs: build_executables
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Prepare release files with unique names
        run: |
          mkdir -p prepared_files
          cp release_files/snipstudio-windows/snipstudio.exe prepared_files/snipstudio-windows.exe
          cp release_files/snipstudio-linux/snipstudio prepared_files/snipstudio-linux
          cp release_files/snipstudio-macos/snipstudio prepared_files/snipstudio-macos
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: SnipStudio ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            prepared_files/snipstudio-windows.exe
            prepared_files/snipstudio-linux
            prepared_files/snipstudio-macos
          body: |
            ## SnipStudio ${{ steps.get_version.outputs.VERSION }}
            
            ### Downloads
            
            - [Windows Executable](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/snipstudio-windows.exe)
            - [Linux Executable](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/snipstudio-linux)
            - [macOS Executable](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/snipstudio-macos)
            
            ### Installation
            
            #### Windows
            Download and run the executable file.
            
            #### Linux/macOS
            ```
            chmod +x ./snipstudio-linux  # or ./snipstudio-macos
            ./snipstudio-linux  # or ./snipstudio-macos
            ```
            
            Built with Python 3.12

  create_branch_release:
    name: Create GitHub Release from Branch
    needs: build_executables
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release_files
          
      - name: Generate version from date
        id: gen_version
        run: echo "VERSION=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          
      - name: Create Release Tag
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          # Check if tag already exists
          if ! git rev-parse "v${{ steps.gen_version.outputs.VERSION }}" >/dev/null 2>&1; then
            git tag -a "v${{ steps.gen_version.outputs.VERSION }}" -m "Automatic build v${{ steps.gen_version.outputs.VERSION }}"
            git push origin "v${{ steps.gen_version.outputs.VERSION }}"
          else
            # If tag exists, add a timestamp to make it unique
            UNIQUE_VERSION="${{ steps.gen_version.outputs.VERSION }}.$(date +'%H%M%S')"
            echo "VERSION=$UNIQUE_VERSION" >> $GITHUB_OUTPUT
            git tag -a "v$UNIQUE_VERSION" -m "Automatic build v$UNIQUE_VERSION"
            git push origin "v$UNIQUE_VERSION"
          fi
      
      - name: Prepare release files with unique names
        run: |
          mkdir -p prepared_files
          cp release_files/snipstudio-windows/snipstudio.exe prepared_files/snipstudio-windows.exe
          cp release_files/snipstudio-linux/snipstudio prepared_files/snipstudio-linux
          cp release_files/snipstudio-macos/snipstudio prepared_files/snipstudio-macos
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.gen_version.outputs.VERSION }}"
          name: "SnipStudio ${{ steps.gen_version.outputs.VERSION }} (Nightly)"
          draft: false
          prerelease: true
          files: |
            prepared_files/snipstudio-windows.exe
            prepared_files/snipstudio-linux
            prepared_files/snipstudio-macos
          body: |
            ## SnipStudio ${{ steps.gen_version.outputs.VERSION }}
            
            Automated nightly build from ${{ github.ref_name }} branch
            
            ### Installation
            
            #### Windows
            Download and run the executable file
            
            #### Linux/macOS
            ```
            chmod +x ./snipstudio-linux  # or ./snipstudio-macos
            ./snipstudio-linux  # or ./snipstudio-macos
            ```
            
            Built with Python 3.12